# Generated by Django 5.0.1 on 2024-01-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
