# Generated by Django 5.0.1 on 2024-01-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created',
        ),
    ]
