# Generated by Django 5.0.1 on 2024-01-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_article_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
